name: zbk_portfolio
description: "my portfolio"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: any
  flutter_svg: any
  flutter_native_splash: any
  equatable: any
  url_launcher: any
  gif: any
  animations: any
  infinite_scroll_pagination: any
  auto_animated: any
  wolt_modal_sheet: any
  animated_splash_screen: any
  page_transition: any
  shimmer: any
  stacked_card_carousel: any
  video_player: any
  chewie: any
  shared_preferences: any
  font_awesome_flutter: any
  flex_color_scheme: ^8.3.0
  web: any
  flutter_tilt: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/gifs/

# Flutter Native Splash configuration
flutter_native_splash:
  # Background color for the splash screen
  color: "#fdfcfd"

  # Image can be a .gif file
  image: assets/gifs/loading.gif

  # Branding image can be added to make it appear in a corner
  # branding: assets/images/branding.png

  # Background color for the splash screen in dark mode
  color_dark: "#fdfcfd"

  # Image for dark mode (can be the same)
  image_dark: assets/gifs/loading.gif

  # Android 12 handles the splash screen differently
  android_12:
    image: assets/gifs/loading.gif
    color: "#fdfcfd"
    icon_background_color: "#fdfcfd"
    image_dark: assets/gifs/loading.gif
    color_dark: "#fdfcfd"
    icon_background_color_dark: "#fdfcfd"

  # Disable fullscreen mode
  fullscreen: false

  # Ensure GIFs work on web -  flutter pub run flutter_native_splash:create
  web: true
